SpadMap:
  term:
    cmd: 'ghostty --title="TermSpad" --class="TermSpad.ghostty"'
    app_id: "TermSpad.ghostty"
    height: 900
    width: 1200
  youdao:
    cmd: 'google-chrome-stable --app-id="dbgilkgiemncodkddegnikoceledjgho"'
    app_id: "chrome-dbgilkgiemncodkddegnikoceledjgho-Default"
    height: 900
    width: 1200
